name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Initialize submodules
        run: git submodule update --init --recursive

      - name: Install Hugo
        run: |
          HUGO_VERSION="0.145.0"
          wget -O hugo.deb "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb"
          sudo dpkg -i hugo.deb
          hugo version

      - name: Build site
        run: hugo --minify

      - name: Deploy via SSH
        run: |
          apt install openssh-client
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa && chmod 600 id_rsa
          eval $(ssh-agent -s)
          ssh-add id_rsa
          ssh -o StrictHostKeyChecking=no ddos@10.20.20.105 "ls /opt/containers/dontddos.me"
          scp -r public/* ddos@10.20.20.105:/opt/containers/dontddos.me/content/
